image: ubuntu:20.04

build:
  stage: build
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - echo -e "deb http://mirrors.aliyun.com/ubuntu/ focal main restricted universe multiverse \ndeb-src http://mirrors.aliyun.com/ubuntu/ focal main restricted universe multiverse  \ndeb http://mirrors.aliyun.com/ubuntu/ focal-security main restricted universe multiverse  \ndeb-src http://mirrors.aliyun.com/ubuntu/ focal-security main restricted universe multiverse  \ndeb http://mirrors.aliyun.com/ubuntu/ focal-updates main restricted universe multiverse  \ndeb-src http://mirrors.aliyun.com/ubuntu/ focal-updates main restricted universe multiverse  \ndeb http://mirrors.aliyun.com/ubuntu/ focal-proposed main restricted universe multiverse  \ndeb-src http://mirrors.aliyun.com/ubuntu/ focal-proposed main restricted universe multiverse\ndeb http://mirrors.aliyun.com/ubuntu/ focal-backports main restricted universe multiverse  \ndeb-src http://mirrors.aliyun.com/ubuntu/ focal-backports main restricted universe multiverse \n" > /etc/apt/sources.list && cat /etc/apt/sources.list
    - apt update && apt -y install sudo git make autoconf cmake build-essential
  script:
    - cmake .
    - make
  artifacts:
    paths:
        - ./*
